language: ruby
rvm:
- 2.1
before_script:
- chmod +x ./script/cibuild
- chmod +x ./script/cideploy
- chmod +x ./script/cibefore
script: 
    - "./script/cibefore"
    - "./script/cibuild"
after_script: "./script/cideploy"
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GH_REF: github.com/llog/llog.git
  - secure: Iu9RWF9HK7N+rnj33oBF6nW0LE2X5zSImwDqlDOg466Xnp8DPJp3s/8rAHnEKUxS88vAy+otdGIiiMr03NY+yWfqSRUqherE++ZonF/TZFwqp1OvADnqEiv6uwp23IVRLpz9b9pRF+U+otyan7UFbCgT1tdGYkz1DtpjFHMZdQHxYDio4JTm9XEx7j37IGmCVN/SkPzqYgpGJbIwMytWpMaysSw4pUQ8po8BRBECZlyQaLJ/q9JcKbb/Qd+eoRFcTojQKwn39q8wJaQ6rgUwFwJEs7MPB/1KGI3v0RhNgncn+bfDixnacqZlHSTIYIVy9M6d/ML3zPyV0uwJeEik0pbXyU66yjsC2Pc0xVDPGmMdRg0OcYTYqfXJRVOzWsZgbSXdMBYThD9Dhg+zVHvlP+D3hcvfdMrD5AOMVJ9338Qf9pMe9jhMzQta+J/uAl23BzDSFNN6BV/IFCQ5m5B5twaRQevRQvls/PyyGtOe31FExBRokBnWPYiVWg2aBRhpRXfSQylnZaAYcVm+xVTL7KjOxrRX/2wkKPG8sJUQU/aPi1qxqhQ24rGxbVs+9UNOuDUtNhNTA1zhJhQ+eYlsTkdh/klpl2RzVZURyj6DoHs4Kx7bhjXpf7kuJzZMobuZXHBlyEZcGvfPMKd2u8N2CJ9C2mp0SxGxEDgE9AFv1CY=
sudo: false
